import { google } from 'googleapis';
import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_ANON_KEY!);

const oauth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  "http://localhost:5000/auth/google/callback"
);

export class GoogleDocsService {
  private static async getAuthClient(advisorEmail: string) {
    const { data: user, error } = await supabase
      .from('ss_account')
      .select('googleAccessToken, googleRefreshToken')
      .eq('accountEmail', advisorEmail)
      .single();

    if (error || !user || !user.googleAccessToken) {
      throw new Error(`Google tokens not found for ${advisorEmail}. User must log in via Google.`);
    }

    oauth2Client.setCredentials({
      access_token: user.googleAccessToken,
      refresh_token: user.googleRefreshToken
    });

    return oauth2Client;
  }

  static async getOrCreateArchiveDoc(courseId: string, advisorEmail: string) {
    const auth = await this.getAuthClient(advisorEmail);
    const drive = google.drive({ version: 'v3', auth });
    const docs = google.docs({ version: 'v1', auth });

    // 1. Check if course already has an archive doc
    const { data: course } = await supabase
      .from('ss_courses')
      .select('courseArchiveDocId, courseName, courseCode')
      .eq('id', courseId)
      .single();

    if (course?.courseArchiveDocId) {
      try {
        await drive.files.get({ fileId: course.courseArchiveDocId });
        return course.courseArchiveDocId;
      } catch (e) {
        console.log("Archive doc not found on Drive, creating a new one.");
      }
    }

    // 2. Create a new Doc if missing
    const docTitle = `ScholarSync Archive: ${course?.courseCode || ''} ${course?.courseName || 'Course'} - ${courseId}`;
    const res = await drive.files.create({
      requestBody: {
        name: docTitle,
        mimeType: 'application/vnd.google-apps.document',
      },
    });

    const docId = res.data.id!;

    // 3. Store docId in course
    await supabase
      .from('ss_courses')
      .update({ courseArchiveDocId: docId })
      .eq('id', courseId);

    // 4. Set some initial header
    await docs.documents.batchUpdate({
      documentId: docId,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: `${docTitle}\nGenerated by ScholarSync\n\n`
            }
          },
          {
            updateParagraphStyle: {
              range: { startIndex: 1, endIndex: docTitle.length + 1 },
              paragraphStyle: { namedStyleType: 'TITLE' },
              fields: 'namedStyleType'
            }
          }
        ]
      }
    });

    return docId;
  }

  static async archiveConsultation(consultation: any, advisorEmail: string) {
    const docId = await this.getOrCreateArchiveDoc(consultation.courseID, advisorEmail);
    const auth = await this.getAuthClient(advisorEmail);
    const docs = google.docs({ version: 'v1', auth });

    const content = this.formatConsultation(consultation);

    await docs.documents.batchUpdate({
      documentId: docId,
      requestBody: {
        requests: [
          {
            insertText: {
              endOfSegmentLocation: {},
              text: content
            }
          }
        ]
      }
    });
  }

  private static formatConsultation(con: any) {
    const date = new Date(con.conDate).toLocaleString();
    return `
--------------------------------------------------
CONSULTATION RECORD - ${date}
--------------------------------------------------
Group: ${con.groupName}
Type: ${con.conType}
Milestone: ${con.conMil}
Status: ${con.conStat}

DISCUSSION SUMMARY:
${con.conSum || 'No summary provided.'}

ASSIGNED ACTION ITEMS:
${con.conAction || 'No action items.'}

ATTENDEES:
${con.conAtt || 'None listed.'}

Archive Date: ${new Date().toLocaleString()}
--------------------------------------------------
\n`;
  }
}
